version: 1.0.{build}
image: Visual Studio 2015
install:
- ps: Set-Service wuauserv -StartupType Manual
- choco install microsoft-build-tools
- set path=C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;%path%
build:
  verbosity: minimal
